name: pos
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  easy_splash_screen: ^1.0.4
  skeletonizer: ^1.4.3
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  hugeicons: ^0.0.11
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_easyloading: ^3.0.5
  persistent_bottom_nav_bar_v2: ^6.1.0
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  pull_to_refresh_flutter3: ^2.0.2
  webview_flutter: ^4.13.0
  collection: ^1.19.1
  midtrans_snap: ^1.0.1
  lottie: ^3.3.1
  ticket_widget: ^1.0.2
  flutter_custom_clippers: ^2.1.0
  image_picker: ^1.1.2
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4 # Dipindahkan ke sini

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animation/
    - .env

# Konfigurasi untuk membuat ikon aplikasi secara otomatis
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
